config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "groups#index"

   resources :homes, only: [:index]

   resources :groups do
    resources :expends, only: [:index]
   end
   resources :expends, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Group, user_id: user.id
    can :manage, Expend, author_id: user.id
    # Define abilities for the user here. For example:

    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expend.rb
class Expend < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group

  validates :name, presence: true
  validates :amount, numericality: { great_than_or_equal_to: 0 }
  validates :author_id, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expends

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :expends, foreign_key: 'author_id'
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expends_controller.rb
class ExpendsController < ApplicationController
  before_action :require_loggin

  layout 'expend'
  def index
    @group = Group.find(params[:group_id].to_i)
    @expends = Expend.where(author: current_user, group: @group).order(created_at: :desc)
  end

  def new
    @expend = Expend.new
    @groups = current_user.groups
  end

  def create
    @group = Group.find(params[:expend][:group_id].to_i)
    @expend = @group.expends.new(author_id: current_user.id, amount: params[:expend][:amount],
                                 name: params[:expend][:name])
    if @expend.save
      flash[:success] = 'expend save successfully'
      redirect_to group_expends_path(@group)
    else
      flash.now[:error] = 'Error : expend didn t save'
      render :new, locals: { expend: @expend }
    end
  end

  def require_loggin
    return if current_user

    redirect_to homes_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout 'group'
  before_action :require_loggin
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      flash[:success] = 'Group save successfully'
      redirect_to groups_path
    else
      flash.now[:error] = 'Error : Group didn t save'
      render :new, locals: { group: @group }
    end
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def require_loggin
    return if current_user

    redirect_to homes_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  layout 'home'
  def index; end

  def require_loggin
    return unless current_user

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expends/index.html.erb
<div class="row p-3">
<div class="col-md-3"> </div>
<div class='col-md-6 d-block mx-auto'>
  <div class='text-secondary w-100 d-flex justify-content-between border border-1 p-3'>
    <%= image_tag("#{@group.icon}.png", :alt => "picture") %>
    <h3><%= @group.name %> </h3>
    
    <h6><%= @group.expends.where(author_id: current_user.id).sum(:amount) %> $ </h6>
  </div>
  <% if @expends.empty? %>
  <h5> Not expends for this user in this group </h5>
  <% else %>

    <% @expends.each do |expend| %>
      <div class='text-secondary w-100 d-flex justify-content-between border border-1'>
        <h3><%= expend.name %> </h3>
        <h6><%= expend.amount %></h6>
      </div>
    <% end %>
  <% end %>
  <a href='<%= new_expend_path %>' class='fixed-bottom btn btn-primary green mt-3 mb-3 d-block mx-auto'> Create expend </a>
</div>
</div>

app/views/expends/new.html.erb
<h1 class="text-secondary text-center"> Create expend </h1>
<% if @groups.empty? %>
  <h6> First go create group </h6>
<% else %>
<div class="row p-3">
<div class="col-md-3"> </div>
<div class= 'border border-1 mt-3 col-md-6 p-3 d-block mx-auto'>
<%= form_with model: @expend, url: expends_path, method: :post, class: 'w-100', local: true do |form| %>
<div class='input-group mb-3'>
  <%= form.label :name, class: 'input-group-text' %>
  <%= form.text_field :name, class: 'form-control'%>
</div>

<div class='input-group mb-3'>
  <%= form.label :amount, class: 'input-group-text' %>
  <%= form.number_field :amount, class: 'form-control'%>
</div>

<div class="input-group mb-3">
    <%= form.label :group_id , class: "input-group-text"%>
    <%= form.select :group_id, @groups.map { |group| ["#{group.name} icon : #{group.icon} ", group.id] },{}, { class:"form-select" } %>
  </div>

<%= form.submit class: 'btn btn-primary bleu w-100' %>
</div>
<% end %>
<% end %>

app/views/groups/index.html.erb
<div class='d-block mx-auto'>
  <% if @groups.empty? %>
  <h5> Not group for this user </h5>
  <% else %>
    
    <% @groups.each do |group| %>
   <div class="row p-3">
    <div class="col-md-3"> </div>
      <a href='<%= group_expends_path(group) %>' class='p-3 col-md-6 text-secondary d-flex justify-content-between border border-1'>
        <%= image_tag("#{group.icon}.png", :alt => "picture") %>
        <h3><%= group.name %> </h3>
        <h6><%= group.expends.where(author_id: current_user.id).sum(:amount) %> $ </h6>
      </a>
      <div class="col-md-3"> </div>
      </div>
    <% end %>
  <% end %>

   </div>
   <div class="fixed-bottom green p-3">
   <a href='<%= new_group_path %>' class=' btn border border-1 d-block w-100 pt-3 pb-3 text-white mx-auto'> Create group </a>
   </div>

app/views/groups/new.html.erb
<h1 class="text-secondary text-center"> Create group of expends </h1>
<div class="row p-3">
<div class="col-md-3"> </div>
<div class= 'border border-1 mt-3 col-md-6 p-3 d-block mx-auto'>
<%= form_with model: @group, url: groups_path, method: :post, class: 'w-100', local: true do |form| %>
<div class='input-group mb-3'>
  <%= form.label :name, class: 'input-group-text' %>
  <%= form.text_field :name, class: 'form-control'%>
</div>
 <h5 class='text-center text-secondary mt-3 mb-3'> choose icon </h5>
<div class='input-group mb-3'>
  <%= form.radio_button :icon, "mac", class:"form-check-input", id: "mac"%>
  <label for="mac" class="form-check-label m-2"> <%= image_tag("mac.png", :alt => "mac") %> </label>
</div>

<div class='input-group mb-3'>
  <%= form.radio_button :icon, "san", class:"form-check-input", id: "san"%>
  <label for="san" class="form-check-label m-2"> <%= image_tag("san.png", :alt => "san") %> </label>
</div>

<div class='input-group mb-3'>
  <%= form.radio_button :icon, "chick", class:"form-check-input", id: "chick"%>
  <label for="chick" class="form-check-label m-2"> <%= image_tag("chick.png", :alt => "chick") %> </label>
</div>

<div class='input-group mb-3'>
  <%= form.radio_button :icon, "taxi", class:"form-check-input", id: "taxi"%>
  <label for="taxi" class="form-check-label m-2"> <%= image_tag("taxi.png", :alt => "taxi") %> </label>
</div>

<%= form.submit class: 'w-100 btn btn-primary bleu' %>
<% end %>

</div>

app/views/homes/index.html.erb
<div class="center">
<h1 class="text-secondary text-center mt-3 p-3 mb-3 pb-3">  Expended </h1>

</div>

<div class="bas">
<a href="<%= user_session_path %>" class='btn btn-primary bleu  w-75 mx-auto d-block'> Login </a>
<a href="<%= new_user_registration_path %>" class='btn btn-light  w-75 mx-auto d-block'> Sign up </a>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bleu">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Expended</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= groups_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_group_path %>">Create group</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="<%= new_expend_path %>">Create expend</a>
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyExpended</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "app", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   
    <% flash.each do |name, msg| %>
      <div class="<%= name %>"><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/expend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyExpended</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "app", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bleu">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= groups_path %>">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
    </svg>
    </a>
    
      
    </div>
  </div>
</nav>
    <% flash.each do |name, msg| %>
      <div class="<%= name %>"><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/group.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyExpended</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "app", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% flash.each do |name, msg| %>
      <div class="<%= name %>"><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyExpended</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "app", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="<%= name %>"><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>